#ifndef LY_COLOR_HPP
#define LY_COLOR_HPP

typedef enum LY_Color{ 
	LY_COLOR_BLACK			= 0,
	LY_COLOR_BLUE			= 1,
	LY_COLOR_GREEN			= 2,
	LY_COLOR_CYAN			= 3,
	LY_COLOR_RED			= 4,
	LY_COLOR_MAGENTA		= 5,
	LY_COLOR_BROWN			= 6,
	LY_COLOR_LIGHT_GREY		= 7,
	LY_COLOR_DARK_GREY		= 8,
	LY_COLOR_LIGHT_BLUE		= 9,
	LY_COLOR_LIGHT_GREEN	= 10,
	LY_COLOR_LIGHT_CYAN		= 11,
	LY_COLOR_LIGHT_RED		= 12,
	LY_COLOR_LIGHT_MAGENTA	= 13,
	LY_COLOR_LIGHT_BROWN	= 14,
	LY_COLOR_WHITE			= 15

} LY_Color;
#endif
